### ISSUE TITLE
BE (+FE): login functionality

### ISSUE THREAD

**Issue by MatejKomlossy** [MatejKomlossy/RedditForStudents#15]
- [x] BE login
- [x] FE login
- [x] create session on BE
- [x] store info about being logged in on FE

**Comment by MatejMagat305** [comment]
toto asi nezatváraj, kým nebudeme mať obaja svoju stranu ...

**Comment by MatejMagat305** [comment]
asi môžeme zatvoriť, ak nesúhlasíš, tak to otvor ...
